# Generated by Django 2.1.7 on 2019-03-31 02:11

import datastore.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50, verbose_name='Formula')),
                ('ccdc', models.CharField(max_length=9, verbose_name='CCDC Identifier')),
                ('dimensionality', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('ueff', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Effective Barrier')),
                ('hdc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(70000), django.core.validators.MinValueValidator(0)], verbose_name='DC Field')),
                ('tc', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Curie Temperature')),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default=datastore.models.default_compound_info)),
                ('checker', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=200, unique=True, verbose_name='DOI')),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default=datastore.models.default_reference_info)),
                ('submitter', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='doi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datastore.Reference'),
        ),
        migrations.AddField(
            model_name='compound',
            name='submitter',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
