# Generated by Django 2.1.7 on 2019-03-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='ccdc',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CCDC Identifier'),
        ),
    ]
