# Generated by Django 2.1.7 on 2019-03-31 02:21

import datastore.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0002_auto_20190330_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=datastore.models.default_compound_info, null=True),
        ),
    ]
