# Generated by Django 2.1.7 on 2019-03-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0003_auto_20190330_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='tau0',
            field=models.FloatField(blank=True, null=True, verbose_name='&tau;<sub>0</sub>'),
        ),
    ]
