# Generated by Django 2.1.5 on 2019-03-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastore', '0004_compound_tau0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='tau0',
            field=models.FloatField(blank=True, null=True, verbose_name='τ₀'),
        ),
    ]
